Results:
  save_results: true
  save_dir: /home/leizongru/lzr_ws/S3PO-GS/output
  save_trj: true
  save_trj_kf_intv: 10
  use_gui: false
  eval_rendering: true
  use_wandb: false
  color_refinement: true
  global_BA: false
  clean_export: true
Dataset:
  type: railway
  sensor_type: monocular
  depth_loss: true
  pcd_downsample: 64
  pcd_downsample_init: 32
  adaptive_pointsize: true
  point_size: 0.01
  dataset_root: /home/leizongru/lzr_ws/railway_data
  scene: scene_05_train
  dataset_path: /home/leizongru/lzr_ws/railway_data/scene_05_train
  gt_pose_root: /home/leizongru/lzr_ws/railway_data/gt_poses
  gt_pose_tolerance_sec: 0.05
  begin: 0
  end: null
  device: cuda:0
  undistort: true
  OriginalCalibration:
    fx: 7267.95450880415
    fy: 7267.95450880415
    cx: 2056.049238502414
    cy: 1232.862908875167
    k1: -0.0790171
    k2: -0.17716
    p1: 0.0
    p2: 0.0
    k3: 1.7629
    width: 4112
    height: 2504
  Calibration:
    fx: 1118.7361995571991
    fy: 1114.3493115194617
    cx: 316.016904358317
    cy: 189.12324084649305
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 632
    height: 384
    depth_scale: 1.0
    distorted: false
Training:
  init_itr_num: 1050
  init_gaussian_update: 100
  init_gaussian_reset: 500
  init_gaussian_th: 0.005
  init_gaussian_extent: 30
  tracking_itr_num: 100
  mapping_itr_num: 150
  global_BA_itr_num: 500
  gaussian_update_every: 150
  gaussian_update_offset: 50
  gaussian_th: 0.7
  gaussian_extent: 1.0
  gaussian_reset: 2001
  size_threshold: 20
  kf_interval: 5
  window_size: 8
  pose_window: 3
  edge_threshold: 1.1
  rgb_boundary_threshold: 0.01
  alpha: 0.98
  kf_translation: 0.08
  kf_min_translation: 0.05
  kf_overlap: 0.9
  kf_cutoff: 0.3
  prune_mode: slam
  prune_num: 1
  single_thread: false
  spherical_harmonics: false
  mapping_itr_nosingle: 10
  a_invalid: 0.5
  a_valid: 0.2
  lr:
    cam_rot_delta: 0.003
    cam_trans_delta: 0.001
opt_params:
  iterations: 30000
  position_lr_init: 0.0016
  position_lr_final: 0.00016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.001
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002
  init_lr: 6
depth:
  patch_size: 10
  mean_threshold: 0.3
  std_threshold: 0.3
  error_threshold: 0.1
  final_error_threshold: 0.15
  min_accurate_pixels_ratio: 0.01
model_params:
  sh_degree: 0
  source_path: ''
  model_path: /home/leizongru/lzr_ws/S3PO-GS/checkpoints/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth
  resolution: -1
  white_background: false
  data_device: cuda
pipeline_params:
  convert_SHs_python: false
  compute_cov3D_python: false
Model:
  checkpoint: /home/leizongru/lzr_ws/S3PO-GS/checkpoints/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth
